### ISSUE TITLE
More Description Needed

### ISSUE THREAD

**Issue by pilotstevek** [yracine/DSC-Integration-with-Arduino-Mega-Shield-RS-232#4]
I am really interested in using your code but your description is so vague that it makes me crazy trying to get it to work. Can you please provide more details on the following steps?

1) The source code for the device type is also provided. You will need to modify this file to setup the proper zone numbers for your system. 
Question:  Where do I modify the zone numbers? I only see a list of zones, so I need to add or remove the ones I don't need? Do the names need to stay the same or can I modify them, if I modify them where else do I need to change them? 

2) Use the provided source code and publish the device type. Pair your SmartThings shield to you hub and then manually change its device type to the one you created. You should now be able to see your new device and will be able to arm/disarm, monitor the state of the zones, trigger the panic alarm, etc.
Question: I paired the shield to the hub and changed the device type but pressing any of the buttons does nothing in the application, however I can see the Arduino shield respond with the TX and RX lights blinking but no response from the alarm. 

3) You can also use the smartapp ArduinoAlarmController to create individual sensors as child Devices. 
Question: How do you do this, just fill out the application with my zone names? Do these names need to correspond to the zone names in the device type?

4) Prior to executing the smartapp, you need to create the Open/Close and Motion Detector device types within your own namespace by using the SmartThing code template within the IDE.
Question: How do you do this? Do the names need to match the device type file? I am completely lost here.

**Comment by yracine** [comment]
Refer to this thread for more help. I'm sorry, but this project was done a long time ago, and I don't have time to give step by step instructions.

https://community.smartthings.com/t/dscalarmsmartthings-guide/9731
